### ISSUE TITLE
Set combobox as disabled

### ISSUE THREAD

**Issue by carbontwelve** [koenpunt/chosen#10]
I am using this plugin to prettify a series of chained combo-boxes and would like to be able to set those further down the line as disabled rather than simply make them invisible to ensure that the user enters data in the right direction.

Is there a way of setting a chosen combo-box as disabled?

**Comment by PureSpider** [comment]
See https://github.com/harvesthq/chosen/issues/67#issuecomment-2170256 for exactly what you want to do :)
