### ISSUE TITLE
Callback getting called twice

### ISSUE THREAD

**Issue by codyleach** [koenpunt/chosen#11]
I'm passing a callback function to the "create_option" option, and I'm noticing that it's getting called twice.

I think I know where the issue is:
- On line 777, the "result_select" code is calling the "select_create_option" function
- On lines 959-961, the "create-option" result is binding to the click event.

This doesn't seem to be happening with the "create_option" set to true.

**Comment by koenpunt** [comment]
Which version are you using, jQuery or Prototype?

**Comment by codyleach** [comment]
I'm using jQuery v1.7.2.

**Comment by koenpunt** [comment]
Doesn't happen to me.. Can you post your code?

**Comment by codyleach** [comment]
I've discovered that if the callback function is appending the new item to the list then all works well. If, however, the callback function isn't appending the item to the list, then the callback function gets called twice.

Here's the code to initialize two select boxes with Chosen, one appending the new item to the list and the other just writing it to the console. The one that writes to the console is actually writing to the console twice:

```
    $('#myselect').chosen({
        create_option: function (term) {
            this.append_option({
                value: 'value-' + term,
                text: term
            });
        },
        persistent_create_option: true
    });

    $('#myselect2').chosen({
        create_option: function (term) {
            console.log(term);
        },
        persistent_create_option: true
    });
```

In the project I'm working on, we're using Knockout.js to handle a lot of our data. We've hooked up it so that the list of items and the selected items in that list are actually managed on a ViewModel. For this reason, I am having the "create_option" callback call another function that's on the Knockout ViewModel. The ViewModel is then sending the new item to the server, adding it to the select box list, and also adding it to the list of selected items.

All is working well, except that the new item gets added twice.

**Comment by koenpunt** [comment]
Ok, I see there are some issues with that, for now you could use `$("#myselect2").trigger( "liszt:updated")`, to close Chosen and stop any events. That is what is called eventually when using `this.append_options({...})`

**Comment by bryandease** [comment]
I am still having this issue as well.  I'm using it for an event sign up form where students enter the school they are attending - being able to use the add feature when the school isn't in the list.  However when I do this:

``` javascript
$('.chzn-select').chosen(
        {
            create_option: function(school)
            {
                var chosen = this;
                $.post('contact/add_school', {school_name:school}, function(data)
                {
                    chosen.append_option(
                    {
                        value: data.id,
                        text: data.school_name
                    });
                }, 'json');
            }
        });
```

The data is being entered into the db twice - and added to the select twice as well.  A tad bit frustrating...

**Comment by bryandease** [comment]
But yes - I did just add:

``` javascript
$('#school').trigger('liszt:updated');
```

right before my ajax call - and that seems to be a temp fix.

**Comment by Samnan** [comment]
I have fixed the issue in my master branch. I noticed when using the mouse, the callback was being called twice. Using keyboard, it worked ok.

https://github.com/Samnan/chosen/blob/master/chosen/chosen.jquery.js
