### ISSUE TITLE
Multi-Select with nested AJAX taxonomy?

### ISSUE THREAD

**Issue by brianfeister** [koenpunt/chosen#15]
First of all - great work on this!  Code looks fabulous!  

It's been a tough bit of researching, but I'm about to fork chosen and integrate your code and also @cjstewart88's [fork for custom templates](https://github.com/koenpunt/chosen).  Will be pretty impressive when it's finished but it's going to take a while.  Just wanted to ask if you've come across anything similar while working on this?

**Comment by koenpunt** [comment]
Yes there is. Select2. http://ivaynberg.github.com/select2/ I see it as a ripoff, an unfair fork of chosen. But others say 'it's open source'. anyway, what's your status on the project?

**Comment by brianfeister** [comment]
Haha, the status is that I'm using Select2 :)

I think Select2 is providing something that Chosen does not - I wish that the Chosen authors would be more open about the fact that they don't (at least from my impression) intend to merge in functionality that doesn't degrade 100% on older browsers, etc.
