### ISSUE TITLE
Creating an option doesn't trigger 'change' event on the form field

### ISSUE THREAD

**Issue by fson** [koenpunt/chosen#16]
When an existing option is selected chosen triggers 'change' event on the underlying select element with

```
@form_field_jq.trigger "change" ...
```

When a new option is selected and created, this event does not trigger.

**Comment by slothbear** [comment]
Thanks for this fix – it is exactly what I needed today. 

I was wondering, is there anything in the event that signifies it was triggered via Adding A New Option – as opposed to Selecting An Existing Option? I'm currently comparing the selection with existing options by hand.

**Comment by koenpunt** [comment]
@slothbear There is currently no event that indicates that there has been an option added. We could probably trigger `liszt:appended` or something alike.
