### ISSUE TITLE
Feature request skip no results message

### ISSUE THREAD

**Issue by gator92** [koenpunt/chosen#20]
Sometimes the no results message is cumbersome, would be nice to have an option for this. Eg, in the jquery version no_results function, a flag to show the no results message:

``` js
if(!this.skip_no_results){
    var no_results_html;
    ...
    this.search_results.append(no_results_html);
}
```

This would probably only make sense if create_option were true, ie, `this.skip_no_results = (this.options.skip_no_results || false) && this.create_option;`

**Comment by chadwhitacre** [comment]
+1

Having both messages seems redundant to me.

![screen shot 2013-04-30 at 9 34 07 am](https://f.cloud.github.com/assets/134455/444111/a8f5b86e-b19a-11e2-8eb6-7704ffc06b6d.png)

**Comment by koenpunt** [comment]
Will look into this soon. PR is welcome

**Comment by gator92** [comment]
Thanks, will make a PR when/if I get the time to deal with coffescript.

**Comment by koenpunt** [comment]
@Gator92 As you may have noticed; I've implemented your suggestion

**Comment by gator92** [comment]
@koenpunt Thank you very much! This feature along with the essential create_option callback makes this the most useful js combo box available.
