### ISSUE TITLE
Chosen 0.9.11 ?

### ISSUE THREAD

**Issue by lephyrius** [koenpunt/chosen#21]
Update to chosen 0.9.11 ?

**Comment by koenpunt** [comment]
Done.

**Comment by lephyrius** [comment]
Looks like you didn't commit it to git.
I don't see any changes earlier than 3 months.

**Comment by koenpunt** [comment]
Take a look at my [option_adding](https://github.com/koenpunt/chosen/tree/option_adding) branch ;)

**Comment by lephyrius** [comment]
ohh! I was just looking in the master branch. :+1:
