### ISSUE TITLE
No more create option

### ISSUE THREAD

**Issue by abrambailey** [koenpunt/chosen#24]
Not sure what happened, but I've suddenly lost the ability to use the create option. I have the following:

$(document).ready(function() {
  $("#business_name").data("placeholder","Select or Create a Business").chosen({
    create_option: true,
    persistent_create_option: true,
    create_option_text: 'Create New Business'
  });
});

This renders a normal Chosen drop menu.. with no create option. I have tried using the js and css from both your option_adding and option-adding branches.  Any idea how to debug this?

**Comment by Mayar** [comment]
jQuery updated to 1.9?

**Comment by koenpunt** [comment]
As @Mayar suggests, which version of jQuery are you using?

**Comment by abrambailey** [comment]
Hi I'm using jquery-rails (2.2.1) 

This gem provides:

jQuery 1.9.1
jQuery UI 1.9.2 (javascript only)
the jQuery UJS adapter
assert_select_jquery to test jQuery responses in Ruby tests

**Comment by Mayar** [comment]
Try this: 
Use branch https://github.com/koenpunt/chosen/tree/option_adding and replace function '$.fn.extend' with original choosen source https://github.com/harvesthq/chosen

**Comment by abrambailey** [comment]
Hey I'm afraid it still isn't working. I have updated my code to:

``` javascript
<script>
$(document).ready(function() {
  try {
    $("#business_name").data("placeholder","Select or Create a Business").chosen({
      create_option: true,
      persistent_create_option: true,
      create_option_text: 'Create New Business'
    });
  }
  catch (e) {
   console.log(e);
  }
});
</script>
```

No errors in the console log... and just a normal chosen drop down rendering.. no where to add option. Also, "Select or Create a Business" is not showing up as a placeholder.. and I only see "select an option."  Sorry about this.

**Comment by abrambailey** [comment]
Hi I think this must have been an asset pipeline thing. I've pushed it into a ruby gem. All good now.

https://github.com/funkdified/chosen-rails

**Comment by koenpunt** [comment]
Ok, closing for now ;)

**Comment by dontfeedthecode** [comment]
I can confirm that I'm running into this issue using jQuery 1.9.1, it's just rendering a standard chosen select list - no sign of an add link :(

``` Javascript
    $('.chzn-select-add').chosen({
        disable_search_threshold: 10,
        create_option: true,
        persistent_create_option: true,
        create_option_text: 'Other'
      });
```
