### ISSUE TITLE
Triggering "Add Options" link as per User's wish

### ISSUE THREAD

**Issue by ghost** [koenpunt/chosen#32]
Thanks Koenpunt, for your effort on tagging the option dynamically in Chosen.js.  A few days before I came around a question in SO, its about **triggering "Add Options" on onBlur event**.  It was interesting and I wanted to give a try, after few hours I found a way to trigger "Add Options" via keypress and onblur event and answered him back by showing it in JSFiddles(http://stackoverflow.com/a/16992383/1671639).

**Feature Request:**
It was a just a fix, it would be cool if we have **some config for triggering the "Add Options"** like
`$(this.form_field).trigger('liszt:updated', eventType, keyCode);`

**examples:** for onblur() trigger
`$(this.form_field).trigger('liszt:updated', onblur, null);`

 triggering Add Option link via key event(eg: enter key)
`$(this.form_field).trigger('liszt:updated', keypress, 13);`

Hope you consider.

Regards,
Praveen Jegan

**Comment by koenpunt** [comment]
Adding items on blur is not desired. You can click on or select the "Add option" item using the arrow keys and press enter to add an item.
