### ISSUE TITLE
public/chosen.jquery.min.js out of sync with chosen/chosen.jquery.min.js

### ISSUE THREAD

**Issue by davereid** [koenpunt/chosen#34]
These files are currently different. Using the version in public/ causes JavaScript errors with "Uncaught TypeError: Object #<Object> has no method 'prop'". Since the upstream  branch has renamed chosen/ to public/, would there be anything wrong with following the same and ensuring that the code in public/ is the most up to date?

**Comment by koenpunt** [comment]
Oh I should delete the chosen dir. public dir should be up to date

**Comment by davereid** [comment]
Hrm, so I'm trying to figure out why I'm getting that JavaScript error with the version in /public.

**Comment by davereid** [comment]
Ah, the issue I'm running into is a bug upstream with jQuery 1.4: https://github.com/harvesthq/chosen/pull/1311
