### ISSUE TITLE
Need support for substrings of existing or previously added options

### ISSUE THREAD

**Issue by pastudan** [koenpunt/chosen#36]
The issue I am having when using the option_adding feature is that a user may want to add an option that is a substring of an existing option. For example, lets say "Daniel" was an option. If a user wanted to add "Dan" they would only be presented with the choice from the dropdown and would not be able to create their option.

I am using release v0.11.1 and noticed there have been quite a few commits since then.. is this something that has been / can be fixed?

It might present a strange UI since it matches some existing options and also shows the "Add Option", but other sites, notably facebook, are doing this. 
![screen shot 2013-08-29 at 11 19 04 am](https://f.cloud.github.com/assets/1296162/1051774/12a35920-10d1-11e3-93cf-33dbe9b884b4.png)

I can take a stab at this this afternoon, and I'll submit a pull request if you think it's a feature you want.

**Comment by pastudan** [comment]
Hah, I am extremely embarrassed for posting this issue. It is supported, and even documented on the front page by adding `persistent_create_option: true` to your config object. Like so:

``` javascript
$(function() {
  $(".chzn-select").chosen({
    create_option: true,
    // persistent_create_option decides if you can add any term, even if part
    // of the term is also found, or only unique, not overlapping terms
    persistent_create_option: true,
    // with the skip_no_results option you can disable the 'No results match..' 
    // message, which is somewhat redundant when option adding is enabled
    skip_no_results: true
  });
});
```

**Comment by koenpunt** [comment]
Yeap :smile:
