### ISSUE TITLE
Cannot add options which are prefixes of existing options

### ISSUE THREAD

**Issue by maerics** [koenpunt/chosen#39]
In the "option_adding" branch it appears that you cannot add new options which are prefixes of existing options.  For example, if "customer-123" is in the list of options you can add "customer-1234" but you cannot add "customer-12" since the "Add option: ..." link does not appear.

[This jsfiddle demonstrates](http://jsfiddle.net/kUFFH/).

**Comment by koenpunt** [comment]
Simple add `persistent_create_option: true` to your options object.:

``` js
$('select').chosen({create_option: true, persistent_create_option: true});
```

**Comment by maerics** [comment]
Thanks :+1:
