### ISSUE TITLE
v1.1.0 release?

### ISSUE THREAD

**Issue by davereid** [koenpunt/chosen#40]
While it would be great to have #38 so we could use this as an extension, it would be nice to have this fork with a 1.1.0 release to match https://github.com/harvesthq/chosen/releases/tag/v1.1.0 because the 1.0 version has major compatibility issues with jQuery < 1.6. Would a new release be possible?

**Comment by koenpunt** [comment]
Here you go: https://github.com/koenpunt/chosen/releases/tag/v1.1.0

**Comment by davereid** [comment]
Thank you so much!

**Comment by slothbear** [comment]
many many _many_ thanks!
