### ISSUE TITLE
New created item value is the same as its text

### ISSUE THREAD

**Issue by maysamsh** [koenpunt/chosen#43]
I'm using this piece of code to add new item on-the-fly:

```
$("#OtherTitlesDropDownList").chosen({
        create_option: function (term) {
            var chosen = this;
            $.get('add.aspx', { sender: 'nonlistedstuff-add-item', newItem: term }, function (data) {
                chosen.append_option({
                    value: 'value-' + data.term,
                    text: data.term 

                });

            });
        },
        persistent_create_option: true,
        create_option:true,
    });
```

When I try to get seleted item's value like this:

```
$('#OtherTitlesDropDownList').bind("change", function () {
        console.log(this.value.toString())
});
```

I get the same input text, not `value-foo`.
When I'm using chrome inspector, there is no request to the `add.aspx`. 

When I remove `create_option:true` it send the request to the `add.asp` but does not append new item to the `select` element.

**Comment by koenpunt** [comment]
You should only specify `create_option` once. See #166 for more info. (although I think you already got your code from there).
