### ISSUE TITLE
Added options not available in the list after saving

### ISSUE THREAD

**Issue by precisionpete** [koenpunt/chosen#44]
If you allow the user to add an option, then reediting the list does not include the new option in the choices... I know this is the base behavior of the select. But by extending select to allow user added options, it would be nice to allow the added option to persist too... 

E.g. Choosing languages.

Select says "English, French, Spanish". User selects "English, Tagalog (added)". Form saves to the database "English, Tagalog". Upon reediting, Chosen shows only "English" and presents the same choices without "Tagalog".

To solve it, I need to grab the list of available options on load and selectively add the missing Tagalog option from the saved database values. It would be great to include this behavior in the plugin. Preferably enabled by the "create_option" feature.

Great plugin BTW... Just needed to find/fix a Bootstrap 3 css file. Would be great to include that too going forward.

Thanks

**Comment by koenpunt** [comment]
I'm not sure what kind of feature you are requesting.. 

But for a bootstrap theme you should look here: https://github.com/harvesthq/chosen/issues/1488#issuecomment-23714840

**Comment by precisionpete** [comment]
I did see that Bootstrap post. What I meant there is it would be nice to include it in the distribuition as e.g. chosen-bs3.css

In terms of my main request... Thinking about it a little more... I realized the plugin does not build the Select. So what I proposed would not be possible. Has to be done before building the select. Not rocket science... Nevermind.

Great plugin. 
Thanks
