### ISSUE TITLE
not changing select "selected" attr 

### ISSUE THREAD

**Issue by timothymarois** [koenpunt/chosen#45]
One thing that is left out here is when you select an option, it does not update the actual select field (most important) because it is being used in a form submission, leaving out this, makes the entire select box useless. Here is a rig I created until someone can fix or show me there is a way to do this properly. Everytime the chosen select changes, it also updates the actual select, using this code

<pre>
$("#myselectbox").chosen().change(function(evt, params) {
  if (params!=undefined) {
    if (params.selected) {
      $('#myselectbox').find('option[value="'+params.selected+'"]').attr("selected",true);
    }
    else {
      $('#myselectbox').find('option[value="'+params.deselected+'"]').removeAttr("selected");
    }
  }
});
</pre>

**Comment by koenpunt** [comment]
Can you show a live example of what's going wrong? Because the plugin does alter the original select and updates Chosen afterwards.

**Comment by LandRush** [comment]
I have run into this as well. It works for newly added items but not for items that are already part of the list. Using @timothymarois fix, it does work.

**Comment by koenpunt** [comment]
I think this is no longer –or never was– an issue with Chosen. If this problem still exists let me know and I'm happy to reopen (and actually look into it)
