### ISSUE TITLE
Able to "add" same name twice, breaks remove

### ISSUE THREAD

**Issue by shiftedpixel** [koenpunt/chosen#46]
Everything works fine with "persistent_create_option: true,"... but i noticed a small glitch.

Example... My select box shows

Miami
Add Option "Miami"

If i add "Miami" a second time, it causes both versions of "Miami" to appear, and i'm unable to remove either.  My preference would be that if "Miami" is already in the list, it doesn't show up to "Add" the option.

Is this possible?

Thanks in advance.

**Comment by koenpunt** [comment]
I'm a bit late to the party, but I believe this was fixed by e3f8d9d51d4de9e3dca4d4473634e4d64676edc2
