### ISSUE TITLE
Search field should specify box-sizing

### ISSUE THREAD

**Issue by dotnetchris** [koenpunt/chosen#50]
The `.chosen-container-multi .chosen-choices li.search-field input[type="text"]` selector specifies the styling on the search field that users enter text in. It is premised upon box-sizing: content-box. When chosen is used with a framework like Foundation that blanket sets box-sizing: border-box the search window displays aberrantly.

I recommend adding the css `box-sizing: content-box !important`

**Comment by koenpunt** [comment]
I guess this commit will fix things: https://github.com/harvesthq/chosen/commit/e4a34493acee355e8c56bcba73063681ea2e2f17 I'll update my branch with upstream soon.

**Comment by dotnetchris** [comment]
looks like they went the opposite direction to make it border-box which would also work

**Comment by koenpunt** [comment]
If this is still an issue please open an issue on the main repo: https://github.com/harvesthq/chosen/issues
