### ISSUE TITLE
Adding option dynamically not working 

### ISSUE THREAD

**Issue by ChunAllen** [koenpunt/chosen#51]
Hi @koenpunt  I'm trying to use the adding option of chosen in my select tag but It's not working.
Here's what I included in my `bower.json` and I'm using `jquery v3.1.0`

```
  "dependencies": {
    "chosen": "https://github.com/harvesthq/chosen/releases/download/v1.1.0/chosen_v1.1.0.zip"
  }
```

and I included the `chosen.jquery.min.js` and `chosen.min.css` in my application.

then when I tried this: 

```
$(function() {
  $(".chosen-select").chosen({
    create_option: true,
    persistent_create_option: true,
    skip_no_results: true
  });
});
```

It makes my select tag to be chosen(searchable) but there is no option on adding a new value.
How can I implement this in my dropdown? 

![687474703a2f2f6e65772e74696e79677261622e636f6d2f6263393331323338616330643937396561633031303434613635356366326664353931316435333636332e706e67](https://cloud.githubusercontent.com/assets/2100728/5042595/405e56b4-6c13-11e4-8ca2-e47c8b7a8a4e.png)

**Comment by koenpunt** [comment]
You should use the archive from my repo: https://github.com/koenpunt/chosen/releases/download/v1.1.0/chosen_v1.1.0.zip
