### ISSUE TITLE
chosen-create-option.jquery.js in chosen_v1.4.2.zip appears to be v1.1.0

### ISSUE THREAD

**Issue by cgatesman** [koenpunt/chosen#53]
chosen-create-option.jquery.js that is packaged in the 1.4.2 release appears to be the older 1.1.0 version and doesn't contain the new chosen 1.4.2 changes.

**Comment by koenpunt** [comment]
The create chosen-create-option file is some local file that got accidentally packaged. The current option creation functionality is in the regular `chosen.jquery.js` in that package.

**Comment by koenpunt** [comment]
But thanks for noticing, I've updated the release zip
