### ISSUE TITLE
Please bring in the changes from harvesthq, namely destroy

### ISSUE THREAD

**Issue by michaelcm** [koenpunt/chosen#55]
Hello,

Hoping that this fork can pull in changes up to 1.5.0 from harvesthq.

This is one issue that would be nice to have fixed:
https://github.com/harvesthq/chosen/issues/2095

I acknowledge I can do it myself in another fork... but hoping not to maintain that too. :)

Thanks,
Michael

**Comment by koenpunt** [comment]
Here you go: https://github.com/koenpunt/chosen/releases/tag/v1.5.1
