### ISSUE TITLE
Cannot obtain id of 'this' (i.e. the active Chosen select) in create_option

### ISSUE THREAD

**Issue by w5m** [koenpunt/chosen#56]
Hi there,

Thank you for providing a very useful mechanism for adding a user-entered option to a database via `create_option`.

Whilst I can successfully pass the newly added option to a PHP script via `$.post`, I'm unable to obtain any kind of identifier to indicate which drop-down the user added this option to. You can see I have attempted to pass this to my PHP script using `this.id`, but unfortunately `this` doesn't have an `id` property and I can't seem to find a way of getting to the identifier. 

```
<script type="text/javascript" src="includes/chosen/chosen.jquery.js"></script>
<script type="text/javascript">
  var config = {
    ".chosen-select": {
      create_option: function(term) {
        var chosen = this;
        $.post("includes/add_option_to_database.php", {term: term, sender: this.id}, function(data) {
          chosen.append_option({
            value: "value-" + data.term,
            text: data.term
          });
        });
      }, 
      skip_no_results: true
    },
    ".chosen-select-deselect"  : {allow_single_deselect:true},
    ".chosen-select-no-single" : {disable_search_threshold:10},
    ".chosen-select-no-results": {no_results_text:"Oops, nothing found!"},
    ".chosen-select-width"     : {width:"100%"}
  }
  for (var selector in config) {
    $(selector).chosen(config[selector]);
  }
</script>
```

My issue has been encountered before and is documented by another user [here](http://stackoverflow.com/questions/12199330/jquery-chosen-plug-get-id).

Any advice/assistance on this issue would be much appreciated.

Many thanks.

**Comment by w5m** [comment]
It turns out the `id` attribute wasn't populated, but the `name` attribute was. I was able to access it via `chosen.form_field.name` (i.e. `this.form_field.name`) in order to send it to the script that adds it to the appropriate database table.

Here's the full script...

```
<script type="text/javascript" src="includes/chosen/chosen.jquery.js"></script>
<script type="text/javascript">
  var config = {
    ".chosen-select": {
      create_option: function(term) {
        var chosen = this;
        $.post("includes/add_option_to_database.php", {term: term, sender: chosen.form_field.name}, function(data) {
          chosen.append_option({
            value: "value-" + data,
            text: data
          });
        });
      }, 
      skip_no_results: true
    },
    ".chosen-select-deselect"  : {allow_single_deselect:true},
    ".chosen-select-no-single" : {disable_search_threshold:10},
    ".chosen-select-no-results": {no_results_text:"Oops, nothing found!"},
    ".chosen-select-width"     : {width:"100%"}
  }
  for (var selector in config) {
    $(selector).chosen(config[selector]);
  }
</script>
```

**Comment by koenpunt** [comment]
Thanks for getting back with this solution. That's sounds like the correct one, as the name is the value that gets send when a form is submitted.
