### ISSUE TITLE
Not working on new version, only works until 1.4.2

### ISSUE THREAD

**Issue by djalmaaraujo** [koenpunt/chosen#58]
### Steps to reproduce

Tell us how to reproduce this issue.

  1. Download new version

  2. Test the public folder

  3. Not working

**Comment by koenpunt** [comment]
Do you get any errors? Or what is not working?

**Comment by djalmaaraujo** [comment]
@koenpunt Hello, thanks for the answer. No errors, just the "Create option" is not appearing.

**Comment by koenpunt** [comment]
Did you open the correct index? And you didn't download from the parent repo?

**Comment by djalmaaraujo** [comment]
Working on 1.5.1, closing the issue, thanks for the fast response. Probably some bad download.
