### ISSUE TITLE
Simulate the change event after add a new option

### ISSUE THREAD

**Issue by matheo** [koenpunt/chosen#6]
After add the new option, to fire the 'change' event is missing
for prototype I've added the following line finalizing Chosen.prototype.select_create_option:

`if (typeof Event.simulate === 'function') this.form_field.simulate("change");`

Seems that the jQuery plugin already tiggers the 'focus'.
TIA :)

**Comment by koenpunt** [comment]
Just like for the original repo, request can only be accepted if made in CoffeeScript and build with `cake build` rather than editing the JavaScript files

**Comment by matheo** [comment]
I don't know how to use it and I don't have the time to do it
so, if it matters for you, the Prototype event is missing there...
