### ISSUE TITLE
pulling data on first dropdown

### ISSUE THREAD

**Issue by roelang** [koenpunt/chosen#9]
this is not an issue but i'd like to populate, via ajax or something, the options when on first dropdown click or arrow down key.

the scenario would be that the selection is not loaded yet except the one, on editing, that is selected.

so if i have selections of countries with value/text, on editing, i will load as part of initialization the existing selected country. then on first dropdown, will pull all available countries.

i would imagine that this is an option with two parameters;

init_option: [] or a function - to populate the existing selected item
first_dropdown: [] or a function - to pull all items.

if you could point me to the right direction how may i start this, i would really appreciate. thanks

**Comment by koenpunt** [comment]
Not something what I'm going to implement. 
Someway you can achieve this is by adding an `click` event with a handler that populates the `<select>` element and then call `$("#form_field").trigger("liszt:updated");` for jQuery or `Event.fire($("form_field"), "liszt:updated");` for Prototype to reflect the changes in Chosen
